### PR TITLE
Add parallelization

### PR DESCRIPTION
**Pull request by marip8**
Various changes from @smith-doug to speed up Trajopt

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
The only thing I would request is that the number of threads used be configurable similar to descartes.

**Comment by marip8** [comment]
Any reason why CI fails on the Trajopt JSON stuff? Seems way outside the additions of this PR

**Comment by marip8** [comment]
> The only thing I would request is that the number of threads used be configurable similar to descartes.

How do you suggest doing this for the `trajopt_sco` additions that were made to static functions?

**Comment by Levi-Armstrong** [comment]
It was most likely a result of the mutex header being added.

**Comment by Levi-Armstrong** [comment]
I have run into this before when adding headers, and had to go through and fix the issues.

**Pull request closed without merging**
