### PR TITLE
Fix bug in getWeightedAvgGradientT1

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Review by rjoomen — APPROVED** [review]
This fixes the glass_upright_example, thanks!

**Comment by rjoomen** [comment]
And what about [this line](https://github.com/tesseract-robotics/trajopt/blob/master/trajopt_ifopt/src/constraints/collision/weighted_average_methods.cpp#L53)?

**Review by rjoomen — COMMENTED** [review]
And what about [this line](https://github.com/tesseract-robotics/trajopt/blob/master/trajopt_ifopt/src/constraints/collision/weighted_average_methods.cpp#L53)?

**Comment by Levi-Armstrong** [comment]
> And what about [this line](https://github.com/tesseract-robotics/trajopt/blob/master/trajopt_ifopt/src/constraints/collision/weighted_average_methods.cpp#L53)?

Yep, another bug!

**Pull request merged**
