### PR TITLE
Add CI for Ubuntu Noble

### PR DESCRIPTION
**Pull request by rjoomen**

### CODE REVIEW

**Comment by rjoomen** [comment]
Not clang-tidy, I think, but gcc, because of the warnings-as-errors option. Or is it the ros-industrial-cmake-boilerplate that runs clang-tidy during a normal build?

**Comment by rjoomen** [comment]
I can take a shot at fixing all the warnings, as I'm using clangd in VSCode that's fairly easy.

**Comment by rjoomen** [comment]
See #411.

**Comment by Levi-Armstrong** [comment]
@rjoomen The MR was merged but there are still errors during the build.

**Comment by rjoomen** [comment]
Can you merge this, so my next shot at fixing the clang-tidy errors will run the CI I'm trying to pass (I can't merge, because required CI checks do not pass and I do not have enough rights to merge anyway)?

**Comment by rjoomen** [comment]
See #412.

**Comment by Levi-Armstrong** [comment]
@rjoomen Still a few clang-tidy errors in trajopt_common/src/utils.cpp.

**Comment by rjoomen** [comment]
See #414.

**Pull request merged**
