### PR TITLE
Expose convex solver settings and set ospq adaptive_rho to default value

### PR DESCRIPTION
**Pull request by Levi-Armstrong**
The adaptive_rho was change because a unit test was failing [here](https://github.com/tesseract-robotics/trajopt/pull/172) but now passes using the default setting indicating that either there was an issue in OSQP or TrajOpt that has been fixed. Have adaptive_rho enable has a signification impact on planning time so it is reverted to default value now that the setting is exposed.

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@marrts I made some slight modification to your changes. Thanks for the improvement.

**Comment by mpowelson** [comment]
Relevant PR when adaptive rho was disabled: https://github.com/tesseract-robotics/trajopt/pull/172

**Review by mpowelson — APPROVED** [review]
Look reasonable. Someone has run some tests and determined that this is a better default?

**Comment by marrts** [comment]
> Look reasonable. Someone has run some tests and determined that this is a better default?

Yes, this went from failing from iterations, which I found needed close to 10 million iterations to solving in about 10k iterations. Substantial speed improvement

**Pull request merged**
