### PR TITLE
Fix box size setting when adjusting penalties

### PR DESCRIPTION
**Pull request by rjoomen**

### CODE REVIEW

**Comment by rjoomen** [comment]
Rebased

**Comment by Levi-Armstrong** [comment]
@rjoomen Are you currently running 22.04?

**Review by Levi-Armstrong — APPROVED** [review]
Good find.

**Comment by rjoomen** [comment]
> @rjoomen Are you currently running 22.04?

Yes, I've been on 22.04 and Humble since I started using Tesseract

**Pull request merged**
