### PR TITLE
Trajopt optimizations

### PR DESCRIPTION
**Pull request by rjoomen**
I noticed significant inefficiencies in creating/updating constraints and costs. With some profiling using perf and hotspot I solved a number of issues leading to a nice speedup for problems with large numbers of variables.

### CODE REVIEW

**Comment by rjoomen** [comment]
Properly reserve SparseMatrix
Before, lots of time spent in coeffRef():
image
After (now SparseVector is the remaining issue):
image

**Comment by rjoomen** [comment]
exprToEigen initialize from triplets

Before, lots of time spent in coeffRef():
image
After (now SparseVector is the remaining issue):
image

**Comment by rjoomen** [comment]
Create SparseVector from doublets

Before:
image
After (all below threshold):
image

**Comment by Levi-Armstrong** [comment]
Awesome! This was on my todo list.

**Review by Levi-Armstrong — APPROVED** [review]

**Pull request merged**
